baseURL = "https://benoitlecallennec-hes.github.io/template_website_course/"
relativeURLs = false
languageCode = "fr"
title = "HE-Arc | 9999.9 Support de cours"
theme = "book"
enableGitInfo = true

[params]
BookSearch = false

[Taxonomies]
  tag = "tags"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "vs"

  