[snippets]
# Directories to scan recursively for snippets
paths = [
  "../1242.1-Langage_C-Profs/Exemples",
  "../1242.1-Langage_C-Profs/Exercices",
  "../1242.1-Langage_C-Profs/Skeletons",
  "static/snippets",
]

extensions = [".c", ".h", ".cpp"]
